export const ROUTES = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  OTP_VERIFY: '/auth/otp-verify',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  CHANGE_PASSWORD: '/settings/change-password',
  QUESTIONS: '/questions',
  QUESTION_DETAIL: '/questions/:id',
  TESTS: '/tests',
  TEST_GENERATE: '/tests/generate',
  TEST_DETAIL: '/tests/:id',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: '/admin/users/:id',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  ADMIN_MODERATION: '/admin/moderation',
  UNAUTHORIZED: '/unauthorized',
} as const;
